config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]

end

app/models/message.rb
class Message < ActiveRecord::Base
  # 名前は必須入力かつ20文字以内
  validates :name , length: { maximum: 20 } , presence: true
  # 内容は必須入力かつ2文字以上30文字以下
  validates :body , length: { minimum: 2, maximum: 30 } , presence: true
  # 数値のみ入力可能。greater_than_or_equal_toはひとつのメソッド
  validates :age, numericality: {greater_than_or_equal_to: 0}, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]

# メッセージ一覧の表示  
  def index
    @message = Message.new
    # Messageを全て取得する。
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end

# メッセージの編集
  def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      flash.now[:alert] = "メッセージの編集に失敗しました。"
      render 'edit'
    end
  end
  
# メッセージの削除
  def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end
  
# ストロングパラメータ
  private
  def message_params
    params.require(:message).permit(:name, :body, :age)
  end
  ## ここまで
  def set_message
    @message = Message.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <div style="background-image:url(<%= asset_path "glid.png" %>)" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag('favicon.ico') %>
</head>
    
    <body>
        <!--Header-->
        <header>
            <div class="row">
                <div id="logo" class="col-sm-12">
                <!--ここにロゴ入れる-->
                <%= image_tag 'logo.png' %>
                </div>
            </div>
            
            <!--ナビゲーションバー-->
            <nav class="navbar navbar-inverse navbar-static-top">
                <!--ナビゲーションバーのヘッダーを設定-->
                <div class="navbar-header">
                    <!--スマホサイズ時のハンバーガーメニューを設定-->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
                        <!--音声ブラウザにメニューがあることを伝えています-->
                        <span class="sr-only">メニュー</span>
                        <!--ハンバーガーメニューの三本線を設定-->
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                <!--ナビゲーションバーの名前-->
                <a href="#" class="navbar-brand">メニュー</a>
                </div>
                <!--ハンバーガーメニュー内に折り畳まれる部分の設定-->
                <div id="gnavi" class="collapse navbar-collapse">
                <!--ナビゲーションバーを使用するメニューですと設定-->
                    <ul class="nav navbar-nav navbar-left">
                        <li><a href="https://masato-narita.github.io/index.html">Home</a></li>
                        <li><a href="https://masato-narita.github.io/about.html">About</a></li>
                        <li><a href="https://masato-narita.github.io/portfolio.html">Portfolio</a></li>
                    </ul>
                 </div>
            </nav>
            
        </header>
        <!--Header-->
        
        
        <div class="container">
            <div class="row">
        <!--Section-->
                    <div class="col-xs-12">
            <h1>Message Board</h1>
                <section>
                     <!--フラッシュメッセージ-->
                      <% if notice %>
                      <div class="alert alert-info">
                      <%= notice %>
                      </div>
                    <% end %>
                      <!--ここまでフラッシュメッセージ-->
                    <%= yield %>
                     </div>
                </section>
            <!--Section--> 
            </div>
        </div>
        
        <!--Footer-->
        
            <footer>
                <div class="row">
                    <div class="col-xs-12">
                    <!--&copy;はコピーライトの記号がでてくる-->
                    <p>&copy; 2016 Masato Narita.</p>
                    </div>
                </div>
            </footer>
        <!--Footer-->
        
        
    </body>
</html>
</html>

app/views/messages/_form.html.erb
<!--エラーメッセージと入力フォーム-->
<%= form_for @message, html: {class: 'form-horizontal'} do |f| %>

  <!--エラーメッセージの表示-->    
  <% if @message.errors.present? %>
    <div class="alert alert-danger">
      <%= alert %>
      <ul>
        <% @message.errors.full_messages.each do |full_message| %>
          <li><%= full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--入力フォーム-->
  <div class="form-group">
    <label for="message_name" class="col-sm-2 control-label">名前:</label>
    <div class="col-sm-10">
      <%= f.text_field :name, :placeholder => "20字以内で入力してください", class: "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <label for="message_age" class="col-sm-2 control-label">年齢:</label>
    <div class="col-sm-10">
      <%= f.text_field :age, :placeholder => "数値のみで入力してください",  class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <label for="message_body" class="col-sm-2 control-label">内容:</label>
    <div class="col-sm-10">
      <%= f.text_area :body, :placeholder => "2字以上、30字以内で入力してください", class: "form-control" %>
    </div>
  </div>

<!--投稿ボタン-->
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-default btn-block pull-right form-control" %>  
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<!--表示されるメッセージ一覧    -->
<div class="panel panel-default">
  <div class="panel-heading">
    メッセージ一覧
  </div>
  
  <div class="panel-body">
    <% @messages.each do |message| %>
        <!-- 名前と年齢を表示-->
      <span class="label label-default"><%= message.name %></span>
      <span class="label label-info"><%= message.age %></span>
      <%= message.body %>
      <!--メッセージの横に(edit)が出てくる-->
      [<%= link_to "編集" , edit_message_path(message) %>
      /
      <%= link_to "削除" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>]<br>
    <% end %>
  </div>
</div>

<% #部分テンプレートを読み込んでいる %>
<%= render 'form' %>